### ISSUE TITLE
'allel' module missing

### ISSUE THREAD

**Issue by ja-Reeve** [MoritzBlumer/inversion_scripts#2]
Hi,

I've been trying to test your script out on my WGS data to identify inversions in _Littorina saxatilis_. I've downloaded your repository from GitHub, and checked the dependencies, but I get the following error whenever I try to run `windowed_pca.py`:

**Script**
`python windowed_pcangsd.py /dir/input.vcf.gz /dir/Metadata.tsv /dir/Local_PCA LG17_SUPER_6:1-$chrom_length 10000 10000 0.05 1 Population Crab,Wave,Other Sex M,F`

**Error**
<img width="637" alt="Screenshot 2024-02-14 at 14 27 34" src="https://github.com/MoritzBlumer/inversion_scripts/assets/82411887/87950df9-e6cd-4f6c-abb8-99d921ae71e6">

Any ideas what's going on?

**Comment by MoritzBlumer** [comment]
Hi and sorry for the slow response!
There are two scripts, `windowed_pcangsd.py` (which uses pcangsd) and `windowed_pca.py` (which uses scikit-allel). Your prompt uses `windowed_pcangsd.py` but the Error refers to the `windowed_pca.py`. Any chance there was a mixup of the two scripts?
